#!/usr/bin/env bash

#TODO: come back an re-conjigure this with the pipeline, i just did it manually with an R-script in the data directory ::blush::
#
#This script is intended to create histograms/density plots of alignment
#quality scores as generated by taxoner/bowtie2
#
unset module
set -u
source ./config.sh
export CWD="$PWD"
#export NUM_FILES=4 #only have four samples, adjust as needed
#export STEP_SIZE=1 #adjust as needed

echo Setting up log files...
PROG=`basename $0 ".sh"`
#Just going to put stdout and stderr together into stdout
STDOUT_DIR="$CWD/out/$PROG"

init_dir "$STDOUT_DIR"

#This is where you would put stuff to find all your samples
#And then make a list of files, change $NUM_FILES, etc.

echo Submitting job...

JOB=$(qsub -V -N scores -j oe -o "$STDOUT_DIR" $WORKER_DIR/hist_maker.pbs)

if [ $? -eq 0 ]; then
  echo Submitted job \"$JOB\" for you. La la la. La. la.
else
  echo -e "\nError submitting job\n$JOB\n"
fi
