#!/usr/bin/env bash

#PBS -W group_list=bhurwitz
#PBS -q standard
#PBS -l select=1:ncpus=6:mem=6gb
#PBS -l walltime=3:00:00
#PBS -M scottdaniel@email.arizona.edu
#PBS -m bea

echo working dir is $(pwd)

cd $PBS_O_WORKDIR

echo started $(date)

if [ -e ./config.sh ]; then
    source ./config.sh
else
    echo "no config"
    exit 1
fi

cd /rsgrps/bhurwitz/scottdaniel/screened-mouse-DNA

rsync $FASTA_DIR/* ./

echo done $(date)
